### ISSUE TITLE
Ability to use locally built images

### ISSUE THREAD

**Issue by olymk2** [drone-plugins/drone-docker#108]
Currently been doing some testing with the plugin, from what i can tell it does not work with out a remote repository ?

I found the --dry-run option from the code which looks like it should do what i need, however I have found that the image is not available for the next step in my builds.

Is there a way to achieve this and if not what's stopping it from working ? a quick look at the codes makes me think it should.

**Comment by bradrydzewski** [comment]
The docker plugin uses docker in docker for security reasons [1], to prevent a malicious author from overwriting images on the host machine. This means images created in the docker step are not available to the host machine docker daemon, and are only available for the lifetime of the plugin.

The target use case for this plugin is building and publishing. If you want to build and run, this plugin isn't the right tool for the job. Instead I recommend looking at options discussed in this thread 
https://discuss.drone.io/t/working-with-docker/220 ... The examples are outdated but the concepts still apply.

[1] https://discuss.drone.io/t/why-some-drone-plugins-run-docker-in-docker/209

**Comment by olymk2** [comment]
Okay thanks for clarifying that, I will have a read and try out the recommendation everything I am doing is on my own private setup.
