### ISSUE TITLE
dns flag throws error about network mode

### ISSUE THREAD

**Issue by olymk2** [drone-plugins/drone-docker#111]
If you add the dns option to your yml file you will be greated with this error, seems like its an issue with docker when using --net=host not sure if thats what drone is using ?

`
409 Conflict: Conflicting options: dns and the network mode`

**Comment by bradrydzewski** [comment]
this is due to use of ambassador container pattern. Open issue https://github.com/drone/drone/issues/1268

**Comment by olymk2** [comment]
Thanks for that @bradrydzewski , quite informative I will try bridged mode basically just trying to get the plugin to pick up a private registry which only has internal dns.
