### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by shinymayhem** [drone-plugins/drone-docker#12]
I've been referred here for using drone to build docker images, but the docs and readme are too vague to really know how to start. Any chance we could get some examples, or instructions for how to use this plugin? Or at least when someone would want to use this plugin and when not to (e.g. building docker containers vs testing and then publishing an already built image, etc)
How is DOCS.md related to README.md? What is the file in the `EOF` and what are we supposed to replace?
I'd be willing to help update the docs if I knew the answers to these questions

**Comment by bradrydzewski** [comment]
@shinymayhem plugins are listed and documented here: http://addons.drone.io/

the docker plugin documentation is here:
http://addons.drone.io/docker/

It includes sample configuration to build and publish a container at completion of the build process.
