### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by donny-dont** [drone-plugins/drone-docker#123]
Add support for building Windows containers.

**Comment by donny-dont** [comment]
https://github.com/docker-library/docker/issues/49 for official DIND on windows.

**Comment by danielkrainas** [comment]
That issue was closed in June, looks like Windows team isn't making DIND-necessary changes a priority on their roadmap.

**Comment by tboerger** [comment]
Than we won't be able to provide natively built windows docker images :(

**Comment by bradrydzewski** [comment]
It is still possible to automatically build and publish windows containers, but we would have to mount the named pipe into the container and connect with the host machine docker socket.

> Running Docker on Linux, the Docker API is usually hosted on Unix domain socket, and since these are in the filesystem namespace, sockets can be bind-mounted easily into containers. On Windows, the Docker API is available on a named pipe. Previously, named pipes where not bind-mountable into Docker Windows containers, but starting with Windows 10 and Windows Server 1709, named pipes can now bind-mounted.

[1] https://blog.docker.com/2017/09/docker-windows-server-1709/

**Comment by tboerger** [comment]
Closing this as we are already building docker images without DinD, mounting the pipe instead.
