### ISSUE TITLE
Static path for docker and dockerd not intuitive for automatically installed docker via community package manager

### ISSUE THREAD

**Issue by gdeverlant** [drone-plugins/drone-docker#131]
The two following lines are creating problems when I try to run docker within Alpine after installing docker via **apk add docker**.

https://github.com/drone-plugins/drone-docker/blob/master/plugin.go#L144
https://github.com/drone-plugins/drone-docker/blob/master/plugin.go#L145

The actual workaround for this problem is to always use **symlinks** inside a Dockerfile like : 

```
RUN ln -s /usr/bin/dockerd /usr/local/bin/dockerd
RUN ln -s /usr/bin/docker /usr/local/bin/docker
```

This should actually dynamically found by this plugin.

**Comment by tboerger** [comment]
This plugin is running on official docker images, so we are using the paths defined by this image, these paths are totally fine because these binaries are not installed by an package manager at all.

**Comment by gdeverlant** [comment]
If the plugin is failing in one case it means that your presumption is not correct. When you do your code you should put as much dynamism instead of statism.

**Comment by tboerger** [comment]
Have you checked that this file really doesn't exist? This error also appears if the binary have been built for a different architecture.

**Comment by gdeverlant** [comment]
The 2 files existed because I was able to run docker -v and dockerd -v but they were simply installed **in /usr/bin/** and not **/usr/local/bin/** by the package manager **apk** on alpine.

Go check the release of the package : https://pkgs.alpinelinux.org/package/v3.6/community/aarch64/docker

**Comment by tboerger** [comment]
Than again, it's built on top of a different base image that put the binaries into the valid /usr/local/bin path.

**Comment by gdeverlant** [comment]
The hard coded path is only valid with this file https://github.com/docker-library/docker/blob/e68e4e6ec06c055a95d441144b0e34d0872f2665/17.03/Dockerfile

**Comment by tboerger** [comment]
It's not supported to install other binaries, feel free to fork the plugin to customize the Docker binary.
