### ISSUE TITLE
publish plugin always pending

### ISSUE THREAD

**Issue by fanux** [drone-plugins/drone-docker#137]
I found the pending bug, and recurrent it. With the docker plugin when publishing, when Dockerfile has some error, publish will pending. example mv a not exist file in Dockerfile 
```
Step 3/4 : RUN mv confd /confd/confd 10s 100 ---> Running in 3f061e24c2bd 10s 101 mv: can't rename 'confd': No such file or directory 11s 102 The command '/bin/sh -c mv confd /confd/confd' returned a non-zero code: 1 
```
then drone always pending...

Dockerfile:
```
FROM centos
RUN cond /confd/confd        # mv a not exist file
```
pipeline:
```
 ...
    publish:
          image: plugins/docker
          ...

          dockerfile: Dockerfile
          insecure: true
```

**Comment by bradrydzewski** [comment]
I was unable to repeat this behavior. Per the below screenshot the step failed and the build completed as expected.

![screen shot 2017-08-06 at 11 19 48 pm](https://user-images.githubusercontent.com/817538/29011037-d1547c56-7afd-11e7-996c-1b2aba87ec65.png)
