### ISSUE TITLE
Error authenticating: exit status 1

### ISSUE THREAD

**Issue by khauser** [drone-plugins/drone-docker#143]
```
docker run --rm \
    -e PLUGIN_TAG=latest \
    -e PLUGIN_REPO=domainname:5000/imagename \
    -e DOCKER_EMAIL=myemail \
    -e DOCKER_USERNAME=username \
    -e DOCKER_PASSWORD=password \
    -e DRONE_COMMIT_SHA=hashtag \
    -e DRONE_VOLUME=/etc/docker/certs.d:/etc/ssl/certs \
    -v $(pwd):$(pwd) \
    -w $(pwd) \
    --privileged \
    plugins/docker
```
fails for me with `level=fatal msg="Error authenticating: exit status 1"`.

Whereas `docker login domainname:5000` succeeds.

Could you help me please?

**Comment by tboerger** [comment]
You are missing PLUGIN_REGISTRY, beside that please follow the issue template and ask this kind of questions on our Gitter chat or on Stackoverflow. This issue tracker is reserved for confirmed issues.

**Comment by azuruce** [comment]
I get the same issue when I have "docker network ls" shows drone_default as one of the bridge.
