### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by ozbillwang** [drone-plugins/drone-docker#146]
I save `Dockerfile` to a subfolder, so when buld the image, I have to give the full path of the file if I need to copy it to image.

Folder structure

```
aws
  |- assume-role
        |- Dockerfile
```

When using  `plugins/docker`, I define below environment: 

      dockerfile: aws/assume-role/Dockerfile

Then I have to change below line in `Dockerfile`

     ADD aws/assume-role/assume-role.sh /usr/local/bin/assume-role.sh

This is weird. I pefer to keep it as local file when copy.

     ADD assume-role.sh /usr/local/bin/assume-role.sh

Hope I explain the problem clearly.

**Comment by tboerger** [comment]
In that case you have to set the context, this is per default `.`. For reference: https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-docker/main.go#L111-L116

**Comment by ozbillwang** [comment]
Thanks, @tboerger 

problem is fixed.
