### ISSUE TITLE
Implement default tags logic

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-docker#150]
I would like to detail my plan to implement an attribute called `default_tags`

```
docker:
  image: plugins/docker
  default_tags: true
```

When this feature is enabled and the event type is tag, drone will automatically tag the image using the standard major, minor, release convention. Some examples:

* `1.0.0` produces docker tags `1`, `1.0`, `1.0.0`
* `1.0.0-rc.1` produces docker tags `1.0.0-rc.1`

If default tags are enabled but the tag is not valid semver ad cannot be parsed, the plugin will default to the `latest` tag like it does today. This may be changed in the future and result in an error and the plugin exiting.

The primary benefit here is that right now we have a somewhat awkward workflow where you have to remember to update the tags in your yaml configuration file before tagging a release (assuming you want to follow this convention of tagging major, minor, release).

**Comment by bradrydzewski** [comment]
Note I am open to other names ... `default_tag`, `auto_tag`, etc ...

**Comment by tboerger** [comment]
Sounds good, but does it also work with v prefixes? Do they get dropped?

**Comment by tonglil** [comment]
Should `-rc` releases be tagged to update the major, minor, or patch versions?

Also I assume `1.1` will only produce docker tags `1` and `1.1`?

**Comment by ozbillwang** [comment]
not really agree. 

I hope at leave one tag need be unique. So every time, with a new build, new tag, for example, `1.0.<drone_build_number>` will be created and push to hub.docker.io

With that, I can lock my plugin in some version, if I don't want to use `latest` as tag.

**Comment by bradrydzewski** [comment]
@tonglil 

> Should -rc releases be tagged to update the major, minor, or patch versions?

pre-releases will not create major, minor or patch versions. For example if we have `1.0.0-alpha.1` it will not create `1.0.0`, `1.0` and `1` tags. It will only create a `1.0.0-alpha.1` tag.

> Also I assume 1.1 will only produce docker tags 1 and 1.1?

`1.1` would create the default tags `1.0.0`, `1.0` and `1`

**Comment by bradrydzewski** [comment]
@tboerger I am also adding a `default_suffix` parameter that can be used in conjunction with the `default_tags` parameter to help with multi-architecture images in the short term.

```
repo: golang
default_tags: true
default_suffix: nanoserver
```
 
Which would produce `golang:1-nanoserver`, `golang:1.9-nanoserver` and `golang:1.9.2-nanoserver`. Pushes to master would produce `nanoserver`.

**Comment by bradrydzewski** [comment]
Initial implementation published and merged. We can perhaps dogfood this feature with the drone plugins, and then refine the logic as needed.

**Comment by tonglil** [comment]
@bradrydzewski is this a typo?

> >  Also I assume 1.1 will only produce docker tags 1 and 1.1?
> 
> refs/tags/1.1 would create the image tags 1.0.0, 1.0 and 1

Do you mean refs/tags/1.1 will create image tags 1.**_1_**.0, 1.**_1_** and 1? If so, I'm good with that.

**Comment by tonglil** [comment]
Also if we can document it that would be dope!

**Comment by tonglil** [comment]
Last comment, can you use `default_tags`, `default_suffix`, and `tags` in conjunction? For example on tag I want the default_tags, as well as some other "manual" tag like `:stable`. Would rather not define another step just for that.

**Comment by dusty** [comment]
When I push master the build is skipped using default_tags.  It works great for when I send a tag.  I was expecting master to create a :latest tag or possibly :master.

Is there a way I can use default_tags and also have it run on a non-tagged push?  Or do I need a separate task with conditions attached to it?

Thanks for this!  I'm loving the idea of it.

```
time="2018-01-23T00:40:32Z" level=info msg="skipping automated docker build for refs/heads/master"
```

Here is my task
```
  docker:
    image: plugins/docker
    repo: dustd/test123
    secrets: [ docker_username, docker_password ]
    default_tags: true
```

**Comment by bradrydzewski** [comment]
@dusty have you confirmed you are running the latest version of the plugin? I know there were some issues with the initial implementation that have been resolved. I would expect a push to master to create a `:latest` tag, assuming master is your default branch.

If you confirm you have the latest version of the plugin (via docker image sha) and you still experience issues, please consider sending a pull request.

**Comment by dusty** [comment]
@bradrydzewski 

Does this look like its the latest?

```
> docker image ls | grep plugin
plugins/docker                    latest              c915a0b93949        7 weeks ago         114MB
plugins/git                       latest              272b4de1492a        2 months ago        66.8MB
```

```
[
    {
        "Id": "sha256:c915a0b939496ad8387a5d30d02269a5ee4ecb0969bff86c64f48565ceeab661",
        "RepoTags": [
            "plugins/docker:latest"
        ],
        "RepoDigests": [
            "plugins/docker@sha256:17e2dd161dd2b3b06f7ba8e3d62a774e41b9d8527a65fc04da3bd2b0fc8881c9"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-11-30T15:15:05.690134643Z",
        "Container": "396e4ab85da97775cf98f145f8f0ad400872e230c7676140dda09b3943e63a1b",
        "ContainerConfig": {
            "Hostname": "3ac1a2f7bcdd",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "2375/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DOCKER_CHANNEL=edge",
                "DOCKER_VERSION=17.10.0-ce",
                "DIND_COMMIT=3b5fac462d21ca164b3778647420016315289034"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "LABEL org.label-schema.build-date=2017-11-30T15:14:55Z org.label-schema.vcs-ref=a31738502accbe9c14ce384f0e9db492723e71fb org.label-schema.vcs-url=https://github.com/drone-plugins/drone-docker.git"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:c66bb15ffdefb68fdc3db874f330262e3761445dabe910088d99105275710f04",
            "Volumes": {
                "/var/lib/docker": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/local/bin/dockerd-entrypoint.sh",
                "/bin/drone-docker"
            ],
            "OnBuild": [],
            "Labels": {
                "org.label-schema.build-date": "2017-11-30T15:14:55Z",
                "org.label-schema.vcs-ref": "a31738502accbe9c14ce384f0e9db492723e71fb",
                "org.label-schema.vcs-url": "https://github.com/drone-plugins/drone-docker.git"
            }
        },
        "DockerVersion": "17.05.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "3ac1a2f7bcdd",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "2375/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DOCKER_CHANNEL=edge",
                "DOCKER_VERSION=17.10.0-ce",
                "DIND_COMMIT=3b5fac462d21ca164b3778647420016315289034"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "sha256:c66bb15ffdefb68fdc3db874f330262e3761445dabe910088d99105275710f04",
            "Volumes": {
                "/var/lib/docker": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/local/bin/dockerd-entrypoint.sh",
                "/bin/drone-docker"
            ],
            "OnBuild": [],
            "Labels": {
                "org.label-schema.build-date": "2017-11-30T15:14:55Z",
                "org.label-schema.vcs-ref": "a31738502accbe9c14ce384f0e9db492723e71fb",
                "org.label-schema.vcs-url": "https://github.com/drone-plugins/drone-docker.git"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 113843259,
        "VirtualSize": 113843259,
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "RootDir": "/var/lib/docker/overlay/7796bec341aea223f3aa43d8afdfd3cd13dbc990b279bfab6895f26a9f87d0a6/root"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:2aebd096e0e237b447781353379722157e6c2d434b9ec5a0d63f2a6f07cf90c2",
                "sha256:6d7e6e9a9c8b1c86944094cc6bf74c454e06e5e6eaae4e2ddb16a0b303ef80db",
                "sha256:f4d7e038b094ca82301396d11846d0183bfa00448717102195414741847771e5",
                "sha256:696cb8887f7a5d621b6e3bccb2bc0c296738a1b263246dfb880899086a4a207d",
                "sha256:7e4c2cf6f5b891072d0371b1fdbcde5940316c702146174404ea6de01e27f5e9",
                "sha256:63e23edbe90a159591e65abafd029f8e382bdb9ae54788bea7e6eaec2bcba31c",
                "sha256:2a331ec9592fbb6528cf78f6208d5bc17928175eb2f278782e57a19f914c9190",
                "sha256:efd78e51cb1492e62698098842ea64e84a41e9213a60b2e0b046a0461718788a",
                "sha256:626b8c8af7bc861d8f86fc738d95eb64a92d15aa89ba25196ee49a8c3e608547",
                "sha256:8a0d30cf57f3597b15a3bf07974bb2140636431efe8579e9787fc8c62c03588a",
                "sha256:2f14618193a14ac0fd878126dd78be6db189ea4eafc3d996f678c50ea95f94f7"
            ]
        }
    }
]

```

**Comment by bradrydzewski** [comment]
As far as I can tell, the `auto_tag` feature is being used to build and publish some of our existing plugins [1][2] and is working as expected for pushes to the default branch (master). Note that `default_tags` is still accepted, but was deprecated.

[1] https://github.com/drone-plugins/drone-codacy/blob/master/.drone.yml
[2] https://beta.drone.io/drone-plugins/drone-codacy/30/8

**Comment by dusty** [comment]
I see.  

Hmm.  Would you mind taking a look at this below?  

If its not a simple answer, then I'll clone it and see if I can figure it out.  I have limited go experience, but I'll give it a shot.

In tags.go it looks like its looking for a match to the default branch if its not a tag
https://github.com/drone-plugins/drone-docker/blob/1fed2373e5cc20a32689526a7c02c55a116ff6ee/tags.go#L57-L65


That looks like its pulled from main.go from the environment
https://github.com/drone-plugins/drone-docker/blob/1fed2373e5cc20a32689526a7c02c55a116ff6ee/cmd/drone-docker/main.go#L200-L204

Then passed in to the function call
https://github.com/drone-plugins/drone-docker/blob/1fed2373e5cc20a32689526a7c02c55a116ff6ee/cmd/drone-docker/main.go#L253-L266


So, I ran a new task to print out my env variables
```
  echo:
    image: busybox
    commands:
      - echo $DRONE_REPO_BRANCH
      - echo $DRONE_REPO_SCM
```

The output shows me DRONE_REPO_BRANCH is not set.  Could this be the issue? 
<img width="604" alt="screenshot 2018-01-22 19 03 42" src="https://user-images.githubusercontent.com/792/35254343-045b93e0-ffa7-11e7-84e2-ea3ab9fb6066.png">

How can I pass that information in?

**Comment by bradrydzewski** [comment]
You need to be running `drone/drone:latest` to ensure you have https://github.com/drone/drone/pull/2274

**Comment by dusty** [comment]
That was it.  Thank you @bradrydzewski 
👍

**Comment by pahanini** [comment]
auto_tags works fine but for tag `1.0.0` a have three images in repo
`1`, `1.0` and `1.0.0` 

Here is a part of `.drone.yml`

```yml
  publish:
    image: plugins/docker
    repo: registry.sima-land.ru:5043/grpc
    auto_tag: true
    auto_tag_suffix: linux-amd64
    when:
      event: [ tag ]
```

is it expected behaviour or not?

**Comment by tboerger** [comment]
This is exactly the expected behavior. And for 1.1.2 you will also get 1.2 and it will overwrite 1.

**Comment by tonglil** [comment]
Could someone who understands the behavior to send a PR to https://github.com/drone/drone-plugin-index for `auto_tag` when it's available in a tagged version of drone? ;)

**Comment by bradrydzewski** [comment]
@tonglil https://github.com/drone/drone-plugin-index/commit/e1ee2c7a14c3d0e5cd9c5b63f6a36b8b83e2e586

FYI this feature works in 0.6 and higher for tag events and 0.8.4 for push events.
