### ISSUE TITLE
custom_dns not correctly used?

### ISSUE THREAD

**Issue by Morriz** [drone-plugins/drone-docker#153]
Hi, when I set `custom_dns` to the ip of the dind host's dns server in `/etc/resolv.conf` (which is actually my kubernetes dns server' `kube-dns.kube-system.svc.cluster.local` with ip `10.0.0.10`), I still get errors when I try to push to a domain that should be resolvable (`kube-registry.kube-system.svc.cluster.local`).

I see that `custom_dns: [ 10.0.0.10, 8.8.8.8 ] `gets expanded to `--dns 10.0.0.10 --dns 8.8.8.8` so I assume it to use those dns servers. I expect your special dind network is not setup correctly, and ultimately defaults to it's own `127.0.0.11` dns server, possibly because the new network has no route to the host's dns server in `/etc/resolv.conf`. But I am just guessing here, as I am not a network expert.

**Comment by bradrydzewski** [comment]
You need to use `custom_dns` or `custom_dns_search` which set the dns for the docker daemon launched inside this plugin. If you have any further support needs please create a thread at [discourse](https://discourse.drone.io).

**Comment by Morriz** [comment]
Tnx. But ‘custom_dns_search” is nowhere to be found in the docs?

**Comment by Morriz** [comment]
I think the used `docker:17.05.0-ce-dind` has dns issues, and your plgin needs `docker-alpine-kubernetes` as base:

https://github.com/moby/moby/issues/30840

**Comment by Morriz** [comment]
If I just use a `docker` image instead of the plugin I can resolve correctly like this:

```
- docker run --rm --dns 10.0.0.10 alpine nslookup kube-registry.kube-system.svc.cluster.local
```

So the plugin does not correctly use the hosts `/etc/resolv.conf`, which is:
```
nameserver 10.0.0.10
search drone.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

**Comment by bradrydzewski** [comment]
> So the plugin does not correctly use the hosts

I do not believe this assessment to be correct.

You are testing with the default docker bridge network, which does not represent how drone is running the plugin. Drone creates a user-defined network for every pipeline execution. The default bridge network and user-defined networks resolve DNS differently [[1]](https://docs.docker.com/engine/userguide/networking/configure-dns/).

> DNS lookup for containers connected to user-defined networks works differently compared to the containers connected to default bridge network.

**Comment by Morriz** [comment]
Yeah, I jut read this whole thread on UDN here: https://discourse.drone.io/t/couldnt-resolve-host-on-clone/281/21

And I start to understand what is going on. I am now hoping to just lookup the ip with nslookup and use that for the docker push registry location (but I don't think that is possible at all):

`registry_ip=$(docker run --rm --dns 10.0.0.10 alpine nslookup kube-registry.kube-system.svc.cluster.local | tail -2 | awk -F ":" '{print $2}')`

**Comment by Morriz** [comment]
I spent 2 days figuring all of this out, only to be able to push to my local registry in a local k8s cluster. Pfffff...
