### ISSUE TITLE
remove dind dependency for those who don't want/need it

### ISSUE THREAD

**Issue by Morriz** [drone-plugins/drone-docker#154]
The more I work with drone, the more I dislike the fact it uses dind. Why not give us the power to choose? And explain that dind does have dns issues when run in a cluster? So far I have only had a lot of headaches with the dind container not resolving dns. I am probably not the only one who wishes to use drone in a cluster.

I know it is more work, but coming from wercker I know what is possible.

**Comment by tboerger** [comment]
The majority of the users don't have problems with the dind image, there are also various people using it within their Kubernetes cluster. If you prefer a different approach it's totally up to you to fork this plugin and change it to your needs. This plugin will stay pretty much like it is because it's widely used and stable.

**Comment by bradrydzewski** [comment]
> And explain that dind does have dns issues when run in a cluster

There are many people using this plugin in kubernetes clusters without any issue. This is only the 2nd time that anyone has mentioned having this problem, so this is not something I typically have to explain.

> Why not give us the power to choose?

You do have the power to choose. You can choose to use this plugin as-is. Or you can choose to fork and alter this plugin. Or you can choose to [create](http://docs.drone.io/creating-custom-plugins-bash/) your own plugin. Or you can choose to not use a plugin and to interact directly with docker.

```
pipeline:
  build:
    image: docker
    commands:
      - docker build -rm -t foo/bar .
      - docker push foo/bar
      - docker rmi foo/bar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

We are not going to change this plugin behavior so I recommend finding an alternative that makes you more comfortable. If you have further questions, per our issue template, please use our [community forum](https://discourse.drone.io/) and create a discussion thread.

**Comment by Morriz** [comment]
I understand and will do so. I would love to be pointed to working examples of drone in a cluster deploying to a registry in that same cluster ;)

But just to leave this for others to find I would like to ask the following here to you as well:

Any idea what I have to set `custom_dns` and `custom_dns_search` to? I need the container to resolve:

`kube-registry.kube-system.svc.cluster.local`

by using these settings found in the hosts `/etc/rsolve.conf`:

```
nameserver 10.0.0.10
search drone.svc.cluster.local svc.cluster.local cluster.local
```

So far I tried:

- to set the hostname to `kube-registry` to have it picked up by `--dns 10.0.0.10 --dns-search kube-system.svc.cluster.local`
- to set the hostname to `kube-registry.kube-system` to have it picked up by `--dns 10.0.0.10 --dns-search svc.cluster.local`
- to set the hostname to `kube-registry.kube-system.svc.cluster.local` to have it picked up by `--dns 10.0.0.10`

**Comment by Morriz** [comment]
@bradrydzewski In your example pipeline build using just the `docker` image, how can I set --dns and --dns-search? If going that route I seem to not have control over that.

**Comment by bradrydzewski** [comment]
In my example, it is mounting the host machine docker socket and therefore connecting to the host machine docker daemon. So whatever is starting docker on the host would need to pass those parameters.

Usually the default options are configured in `/etc/default/docker`

**Comment by Morriz** [comment]
That wouldn't work, as kubernetes is doing all the work. I see no way out of this mess. Am I never able to resolve a cluster ip with a drone plugin?

**Comment by bradrydzewski** [comment]
> That wouldn't work, as kubernetes is doing all the work

Are you sure about this? Did you not provide the drone agent with the host machine docker daemon socket, mounted as a volume?

> Am I never able to resolve a cluster ip with a drone plugin?

If your configuration does not support user-defined networks perhaps you need to create an issue with Docker or Kubernetes?

**Comment by Morriz** [comment]
Ok, would you then please be so kind to give me an example? I should be able to resolve my cluster domain names without having to change anything outside drone, right?

**Comment by bradrydzewski** [comment]
Please try my recommended solution and report back if it is not working:

```
pipeline:
  build:
    image: docker
    commands:
      - docker build -rm -t foo/bar .
      - docker push foo/bar
      - docker rmi foo/bar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by Morriz** [comment]
It fails but the drone ui quickly erases the output and jut shows `exit code 1`. How can I capture the logs?

**Comment by bradrydzewski** [comment]
do you need to enable trusted mode in the user interface?  This is required to mount a volume. It can be enabled in the repository settings screen, by a drone administrator.

**Comment by Morriz** [comment]
No, I have set that correctly already before.

**Comment by bradrydzewski** [comment]
This issue thread is starting to turn into a chat. Lets move this to https://discourse.drone.io

**Comment by Morriz** [comment]
I can't see nothing in the drone agent log output beside it reporting it exited with 1

**Comment by bradrydzewski** [comment]
I cannot repeat this behavior, this is what I see:

<img width="959" alt="screen shot 2017-10-01 at 9 10 52 am" src="https://user-images.githubusercontent.com/817538/31056564-8790a8ae-a688-11e7-9e23-24136187e631.png">

**Comment by bradrydzewski** [comment]
I am closing this thread. I believe the original issue, requesting this plugin to not use docker in docker, was addressed.

The appropriate forum for this type of discussion we are now having is discourse. Please create a thread at [discourse.drone.io](https://discourse.drone.io/) if you would like to continue this discussion, and I will be happy to answer questions there.
