### ISSUE TITLE
[feature-request] Ability to push an image without building

### ISSUE THREAD

**Issue by leodotcloud** [drone-plugins/drone-docker#163]
Currently it's not possible to just push a docker image using this plugin. The docker image could have been built by an upstream plugin. I could create a new plugin, but it's just a duplication of most of the code in this repo.

**Comment by tboerger** [comment]
If you are anyway already building the image differently I would suggest to use the library/docker image and simply call login and push with that.

**Comment by easysg** [comment]
use library/docker,:
```bash
docker login -u $${docker_username} -p $${docker_password}
```
Cannot perform an interactive login from a non TTY device

**Comment by tboerger** [comment]
This plugin always builds and pushs the image, something else is out of the scope of this plugin.
