### ISSUE TITLE
Error authenticating: exit status 125

### ISSUE THREAD

**Issue by cusspvz** [drone-plugins/drone-docker#164]
I think it is related with the latest release, going to check with `17.05` tag if it works.

```
+ /usr/local/bin/dockerd -g /var/lib/docker
0s
2
time="2017-12-06T12:32:59Z" level=fatal msg="Error authenticating: exit status 125"
```

**Comment by cusspvz** [comment]
It worked with the `image: plugins/docker:17.05` configuration. Seems it is a bug that affects only the `17.10` and current `latest` version.

So for anyone that needs it right away, you just have to put the latest working version at the plugin image:
```diff
   publish_docker_image:
-    image: plugins/docker
+    image: plugins/docker:17.05
```

**Comment by bradrydzewski** [comment]
you need to remove the email (eg DRONE_EMAIL) from your secrets. If you try to login using an email docker will fail to authenticate.

**Comment by Ulexus** [comment]
Reverting to 17.05 does work for me, but I do **NOT** have any `DRONE_EMAIL` or `DOCKER_EMAIL` secret defined:

```
$ drone secret ls XXXXX/yyyyy
KUBERNETES_SERVER
Events: push, tag, deployment
Images: <any>
KUBERNETES_TOKEN
Events: push, tag, deployment
Images: <any>
KUBERNETES_CERT
Events: push, tag, deployment
Images: <any>
DOCKER_USERNAME
Events: push, tag, deployment
Images: <any>
DOCKER_PASSWORD
Events: push, tag, deployment
Images: <any>
```

Which leads to:

```
+ /usr/local/bin/dockerd -g /var/lib/docker
time="2018-06-04T00:44:06Z" level=fatal msg="Error authenticating: exit status 125"
exit code 1
```

**Comment by peakingTony** [comment]
what happened to me is as the same as @Ulexus , how to work it out guys

**Comment by peakingTony** [comment]
I guess it should be the problem of harbor repository  https ,it is OK when I changed the harbor repository for https

**Comment by Ulexus** [comment]
@peakingTony Interestingly, using `plugins/docker:17.12` now works for me.

**Comment by tboerger** [comment]
Seems to be outdated.

**Comment by tboerger** [comment]
You should not use that old version of this plugin anyway, it doesn't receive any updates. 17.12 is nearly 2 years old ;)

**Comment by shqear93** [comment]
@tboerger I already tried many versions! even latest doesn't work

```
kind: pipeline
name: default

steps:
  - name: docker-build-publish
    image: plugins/docker
    settings:
      repo: "209.X.X.X:5000/test"
      username: admin
      password: XX#XXX
```

and I have weird case, I spin up my own private registry and logged-in using wrong username and password and it even works! so I think it's related somehow , maybe the problem in my registry

**Comment by tboerger** [comment]
You are missing registry additionally to repo setting

**Comment by shqear93** [comment]
@tboerger same! I tried registry either it doesn't work, also tried insecure attribute because my registry is private and ssl is not enabled, in the end I switched to `docker:dind` and error finally gone
