### ISSUE TITLE
Warn user if plugins/docker is running in a non Privileged mode

### ISSUE THREAD

**Issue by arno01** [drone-plugins/drone-docker#170]
Hi,

I have been struggling with [plugins/docker unable to pull the image when using a custom Docker registry][1] due to it was not running in a privileged mode which was not apparent, until I went into the drone-dind, paused the plugins/docker container before it has failed and did inspect it.

So, I think it might have some sense to have some mechanism to warn a user if plugins/docker is running in a non Privileged mode.

[1]: https://discourse.drone.io/t/solved-plugins-docker-cannot-pull-the-image-from-a-custom-docker-registry/1748

I am wondering, is this expected that plugins/docker container is automatically starting in a privileged mode without having the ``privileged: true`` in ``.drone.yml`` ?

It is clear that whoever uses ``plugins/docker`` would need to run it in a privileged mode.

But how would one prevent a non-admin user from setting ``privileged: true`` (when the repo ``Trusted: false``), while keeping the same behavior, except when the plugins/docker is running from a custom docker registry?

How does Drone decide that ``plugins/docker`` needs to run in a privileged mode and is this valid only to this particular plugin when it is pulled from the official Docker Hub registry?

**Comment by bradrydzewski** [comment]
Drone automatically runs `plugins/docker` in privileged mode.

**Comment by bradrydzewski** [comment]
Let's use the discourse forum for Q&A

**Comment by myers** [comment]
(for those following along later the thread he's talking about is: https://discourse.drone.io/t/solved-plugins-docker-cannot-pull-the-image-from-a-custom-docker-registry/1748)
