### ISSUE TITLE
Azure CR plugin

### ISSUE THREAD

**Issue by jpds** [drone-plugins/drone-docker#191]
It would be neat if this plugin had integration for Azure Container Registry.

There is some example code for the Azure SDK at: https://github.com/Azure-Samples/azure-sdk-for-go-samples/pull/215

**Comment by jpds** [comment]
I managed to get this working with plain 'headless' docker and a service principal per the Microsoft documentation:

- https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal

**Comment by bradrydzewski** [comment]
This is not something I plan to work on, but would be happy to accept a pull request.
