### ISSUE TITLE
'build_args' parameter isn't actually passed on

### ISSUE THREAD

**Issue by rustycl0ck** [drone-plugins/drone-docker#195]
As mentioned in the docs [here]( drone-plugin-index/content/drone-plugins/drone-ecr/index.md ) - `build_args : custom arguments passed to docker build`, I should be able to pass custom build arguments like `--network=host`. But these arguments aren't passed to the docker build command even if provided in the `.drone.yml` file.

**Comment by bradrydzewski** [comment]
build args refers to the actual `--build-args` command line flag provided by the docker client [1]. it does not refer to custom flags. You can see here where we pass the build args:
here https://github.com/drone-plugins/drone-docker/blob/master/docker.go#L210

> I should be able to pass custom build arguments like --network=host

this plugin is tightly controlled. for security reasons we would not expose --network=host.  You can always fork and customize the plugin, or you can consider mounting the host machine docker socket if you want more control over docker.

[1] https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg
