### ISSUE TITLE
Docker build layers caching

### ISSUE THREAD

**Issue by spacentropy** [drone-plugins/drone-docker#196]
Hi! We use multi-stage Dockerfile builds for .NET Core projects. In these builds we cache a lot of things (packages, built dlls, etc) in intermediate layers. Our Dockerfile looks like this:
```
# copy csproj and restore as distinct layers
COPY src/*.sln .
COPY src/Dodo.GeoService.CrossCutting/*.csproj ./Dodo.GeoService.CrossCutting/
COPY src/Dodo.GeoService.Redis/*.csproj ./Dodo.GeoService.Redis/
COPY src/Dodo.GeoService.Grpc/*.csproj ./Dodo.GeoService.Grpc/
COPY src/Dodo.GeoService.Grpc.SampleClient/*.csproj ./Dodo.GeoService.Grpc.SampleClient/
COPY src/Dodo.GeoService.Domain/*.csproj ./Dodo.GeoService.Domain/
COPY src/Dodo.GeoService.DataServices/*.csproj ./Dodo.GeoService.DataServices/
COPY src/Dodo.GeoService.Tests/*.csproj ./Dodo.GeoService.Tests/

COPY NuGet.config /root/.nuget/NuGet/NuGet.Config

RUN dotnet restore 

# copy and build everything else
COPY src/Dodo.GeoService.CrossCutting/. ./Dodo.GeoService.CrossCutting/
COPY src/Dodo.GeoService.Redis/. ./Dodo.GeoService.Redis/
COPY src/Dodo.GeoService.Grpc.SampleClient/. ./Dodo.GeoService.Grpc.SampleClient/
COPY src/Dodo.GeoService.Grpc/. ./Dodo.GeoService.Grpc/
COPY src/Dodo.GeoService.Domain/. ./Dodo.GeoService.Domain/
COPY src/Dodo.GeoService.DataServices/. ./Dodo.GeoService.DataServices/
COPY src/Dodo.GeoService.Tests/. ./Dodo.GeoService.Tests/

RUN dotnet build -c Release

WORKDIR /app/Dodo.GeoService.Tests
RUN dotnet test -c Release --no-restore --no-build
```
We used static machine (with usual docker-engine and TeamCity) and most of these stages were cached, builds were blazing fast, because when you don't change packages or code inside solution subprojects, they are brought from cache. 

It seems that this line prevents this from happening by deleting everything left after build. 
https://github.com/drone-plugins/drone-docker/blob/9589237541a649677691284285f71ee2622065d5/docker.go#L189

Maybe we could have this as a parameter? Is there something that we don't know? How other users cache their Dockerfile layers?

Thanks

**Comment by bradrydzewski** [comment]
👋 hey there, please see the following comments in our mailing list where this is discussed, including different options you might have:
https://discourse.drone.io/t/docker-build-does-not-use-cache-drone-cli-exec/2359/2
https://discourse.drone.io/t/docker-plugin-delete-cached-layer-in-multistage-build/1010/5

we may at some point support the cache-from flag which could also help reduce build times. I recommend subscribing to this existing thread for updates:
https://github.com/drone-plugins/drone-docker/pull/151
