### ISSUE TITLE
Build from Tag not working..

### ISSUE THREAD

**Issue by burdzand** [drone-plugins/drone-docker#209]
Using tag to create a image:

tags:
      - "${DRONE_TAG}"

/usr/local/bin/docker build --rm=true -f Dockerfile -t . --pull=true

always get this error:
invalid argument "" for "-t, --tag" flag: invalid reference format

**Comment by tboerger** [comment]
You are not providing any additional information like the used Drone version, or even the plugin version. I don't think that anybody could give useful feedback so far.

**Comment by burdzand** [comment]
Right, I am using Drone 1.0.0, plugin/docker 17.12
  with Gogs

**Comment by bradrydzewski** [comment]
The DRONE_TAG variable is only populated for tag events. This means the value is going to be empty for other event types. You should therefore limit the step to tag events to avoid this error.

```
when:
  event:
  - tag
```
