### ISSUE TITLE
Document 'when' qualifier

### ISSUE THREAD

**Issue by gtaylor** [drone-plugins/drone-docker#22]
For example, we use 'when' to only publish images on a tag event. This seems to be a frequently asked question, so explicitly adding it to the docs is probably worthwhile.

**Comment by tboerger** [comment]
That should be documented on the core documentation, better highlighted of course...

**Comment by bradrydzewski** [comment]
The `when` section is heavily documented and includes an example with conditional tag logic http://readme.drone.io/usage/artifacts/#conditions:ae3f77d4da25cb721d64daf2ef987305

Do you think people are going straight to the plugin documentation and not reading the actual deployment / notification / artifact sections of the docs? Maybe we need to find a way to highlight this sort of central documentation from the individual plugin docs?

Completely agree we need a FAQ. I'm thinking we have a FAQ for each major section (Installation, Usage, etc). Thoughts?

**Comment by gtaylor** [comment]
Oh wow, I definitely didn't think to look under Artifacts. That was easy to miss. 

If I am understanding correctly, this applies to notify and deploy steps as well? If that is indeed the case, maybe there's a better place for this.

**Comment by bradrydzewski** [comment]
Yes, in fact I have it documented under all three sections at the moment:
http://readme.drone.io/usage/artifacts/#conditions:ae3f77d4da25cb721d64daf2ef987305
http://readme.drone.io/usage/notify/#conditions:d1fea7f63b32cc4bab67588d2fde8aa7
http://readme.drone.io/usage/deploy/#conditions:0814af543608f4fd171b2e9cf43d9917

I think maybe a FAQ is a great way to re-direct people to documentation they may have missed. Or perhaps at the bottom of every plugin page we add some "suggested reading" links. We could add this to the template itself so it renders automatically for every plugin.

Just some ideas :smile:

**Comment by gtaylor** [comment]
I don't know if this was helpful, but for some reason I was looking for this under the 'build' section documentation. Is it valid there, too?
