### ISSUE TITLE
what is the auth token for the registry

### ISSUE THREAD

**Issue by yizhishang** [drone-plugins/drone-docker#235]

**Comment by tboerger** [comment]
There is no attribute to set any auth token within the plugin.

**Comment by yizhishang** [comment]
you can find the attribute in the page "http://plugins.drone.io/drone-plugins/drone-docker/"

**Comment by yizhishang** [comment]
> There is no attribute to set any auth token within the plugin.

you can find the attribute in the page "http://plugins.drone.io/drone-plugins/drone-docker/"

**Comment by tboerger** [comment]
In that case the docs are not up to date, https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-docker/main.go doesn't provide any `auth` attribute.

**Comment by mattbucci** [comment]
1 year later and the docs are still wrong..

**Comment by mawis** [comment]
Indeed … I was caught by this trap today as well.
Is this plugin usable with a docker account that has two factor authentication enabled at all?

**Comment by Berjou** [comment]
> Is this plugin usable with a docker account that has two factor authentication enabled at all?

I was able to make it work with two factor authentification just by filling the `password` field with an access token.

**Comment by mawis** [comment]
> I was able to make it work with two factor authentification just by filling the `password` field with an access token.

Indeed, I can confirm that works. Thanks!
