### ISSUE TITLE
Please document build_args_from_env

### ISSUE THREAD

**Issue by yutannihilation** [drone-plugins/drone-docker#246]
After struggling to use a secret as build-time envvar, I found undocumented parameter `build_args_from_env`. This seems very helpful. Can you add a brief description here?

http://plugins.drone.io/drone-plugins/drone-docker/

(I'm happy to create a PR for this, but I don't find the source of the doc...)

**Comment by Leboudin** [comment]
+1 too!

**Comment by tboerger** [comment]
Please provide a PR to https://github.com/drone/drone-plugin-index/blob/master/content/drone-plugins/drone-docker/index.md for adding information about it.

**Comment by yutannihilation** [comment]
Thanks, will do!

**Comment by yutannihilation** [comment]
@Leboudin Thanks for the nice example! Can I use it in my PR?

**Comment by Leboudin** [comment]
> @Leboudin Thanks for the nice example! Can I use it in my PR?

Sure!

**Comment by yutannihilation** [comment]
Thanks :+1:
