### ISSUE TITLE
Cannot modify this image name “plugins/docker” when use drone ci

### ISSUE THREAD

**Issue by adoo123** [drone-plugins/drone-docker#258]
Because i want to push this image to my registry,when I change the image name "plgins/docker" to "xxx/plugins-docker", I couldn't use it to build my image, this is Error:

+ /usr/local/bin/dockerd --data-root /var/lib/docker
--
2 | + /usr/local/bin/docker version
3 | Client: Docker Engine - Community
4 | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
5 | Version:           18.09.3
6 | API version:       1.39
7 | Go version:        go1.10.8
8 | Git commit:        774a1f4
9 | Built:             Thu Feb 28 06:32:01 2019
10 | OS/Arch:           linux/amd64
11 | Experimental:      false
12 | time="2019-12-19T04:43:49Z" level=fatal msg="exit status 1"

**Comment by tboerger** [comment]
You got to add your custom docker image to this environment variable list of your drone runner, otherwise it won't work: https://docker-runner.docs.drone.io/installation/reference/drone-runner-privileged-images/

**Comment by adoo123** [comment]
Thank you!

**Comment by rluvaton** [comment]
> You got to add your custom docker image to this environment variable list of your drone runner, otherwise it won't work: https://docker-runner.docs.drone.io/installation/reference/drone-runner-privileged-images/

@tboerger This link is dead, I'm having the same issue, do you have updated link

**Comment by tboerger** [comment]
Even that the link is dead, just following the path on the Drone docs can'Ät be that hard... LMGTFY: https://docs.drone.io/runner/docker/configuration/reference/drone-runner-privileged-images/

**Comment by rluvaton** [comment]
Thank you
