### ISSUE TITLE
How to set --pull = false when docker build

### ISSUE THREAD

**Issue by YahuiWong** [drone-plugins/drone-docker#261]
When --pull = true, it is really slow and it affects the build efficiency

**Comment by ahmetwaly** [comment]
Anyone figured out how to do this ?

**Comment by tboerger** [comment]
Just provide pull_image: false within the settings.

**Comment by MYZ6** [comment]
> Just provide pull_image: false within the settings.

Why not work? It pulls the base image every build, for me it's too expensive, AWS charge for all the data transfer.

**Comment by tboerger** [comment]
https://github.com/drone-plugins/drone-docker/blob/master/docker.go#L230-L232 adds the flag, https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-docker/main.go#L269 maps the flag to the `Pull` attribute, https://github.com/drone-plugins/drone-docker/blob/master/cmd/drone-docker/main.go#L170-L174 defines the flag, and `pull_image: false` gets translated to the env variable `PLUGIN_PULL_IMAGE`. So if you define `pull_image: false` within the settings it definitily does append the `--pull=false` flag.
