### ISSUE TITLE
Security Issue: plugin leaks hostnames unencrypted to 3P/WAN

### ISSUE THREAD

**Issue by sneak** [drone-plugins/drone-docker#263]
Creating another issue to track the security bug (data leak) that is a consequence of #193.

When using plugins/docker for builds, the internal docker setup sends DNS requests from the build **unencrypted** to Google's DNS servers at `8.8.8.8` and `8.8.4.4`.  This is a security bug, as it tells your ISP and anyone else listening what hostnames you are looking up!

**Comment by ashwilliams1** [comment]
closing as duplicate of #193
