### ISSUE TITLE
when use private registry connect: no route to host

### ISSUE THREAD

**Issue by 82253452** [drone-plugins/drone-docker#265]
+ /usr/local/bin/docker push 172.17.10.121:5000/a82253452/kj-admin/test:47
--
125 | The push refers to repository [172.17.10.121:5000/a82253452/kj-admin/test]
126 | Get http://172.17.10.121:5000/v2/: dial tcp 172.17.10.121:5000: connect: no route to host
127 | time="2020-03-11T13:29:29Z" level=fatal msg="exit status 1"

**Comment by tboerger** [comment]
I'm using a private registry on a daily base. This must be some local network issue on your side.

**Comment by 82253452** [comment]
> I'm using a private registry on a daily base. This must be some local network issue on your side.

thanks for your reply
I deployed drone to show off in swarm ，Is this the problem

**Comment by tboerger** [comment]
I can't say anything to your network, that's up to you. I can just confirm that this plugin is working totally fine as long as the private registry can be properly resolved. On you debugging keep in mind that this plugin is starting a Docker in Docker setup, so you should use public resolveable domains or addresses for your registry.

**Comment by Veitor** [comment]
> * /usr/local/bin/docker push 172.17.10.121:5000/a82253452/kj-admin/test:47
>   --
>   125 | The push refers to repository [172.17.10.121:5000/a82253452/kj-admin/test]
>   126 | Get http://172.17.10.121:5000/v2/: dial tcp 172.17.10.121:5000: connect: no route to host
>   127 | time="2020-03-11T13:29:29Z" level=fatal msg="exit status 1"

same promble. 

DNS resolution is normal, but routing is not working. I think it has something to do with Docker's network configuration.

Do you remember how you solved it in the end?

@82253452
