### ISSUE TITLE
Push in custom Registry doesn't seem to work

### ISSUE THREAD

**Issue by athieriot** [drone-plugins/drone-docker#29]
Hello,

I have been trying to use ```drone-docker``` in order to push images into our custom Registry and there seem to be a problem with authentication.

First of all, please note that we use Docker Registry v2. It's secured with TLS and we configured authentication to use JWT tokens. This setup has proved to work just fine with Docker client.

The peculiar thing is that if I look at the log, at the beginning of the build, I can clearly see that ```drone-docker``` successfully logged in:

      [info] Pulling image plugins/drone-docker:latest
      $ /usr/bin/docker -d
      WARNING: login credentials saved in /.docker/config.json
      Login Succeeded

However, at the end, pushing fails:

      $ /usr/bin/docker push registry.company.com/company/jenkins-slave:latest
      The push refers to a repository [registry.company.com/company/jenkins-slave] (len: 1)
      e1f3183388e0: Preparing
      unauthorized: authentication required
      [info] build failed (exit code 1)

I find weird that the config file is stored at the root of the machine and not in the user directory.
Do you think it might be related?

Thank you for your help

Aurélien

**Comment by tboerger** [comment]
Without information about your config nobody can help you.

**Comment by athieriot** [comment]
Sorry.
I tried to be as descriptive as possible and forgot the obvious !

Here is what I used:

   publish:
     docker:
       registry: registry.company.com
       username: drone
       password: pa$$word
       email: support+drone@company.com
       repo: registry.company.com/company/jenkins-slave
       file: jenkins-slave/Dockerfile
       context: jenkins-slave
       tag: latest

It's actually the sole content of my .drone.yml file as I don't need to build anything for this repo.

I have also try to use the ```auth``` property, on top of the rest, populated with whatever token is in my ~/.docker/config.json

   publish:
     docker:
       registry: registry.company.com
       username: drone
       password: pa$$word
       email: support+drone@company.com
       repo: registry.company.com/company/jenkins-slave
       auth: T0K3N==
       file: jenkins-slave/Dockerfile
       context: jenkins-slave
       tag: latest

**Comment by athieriot** [comment]
Ok. My bad -_-

There was an access restriction misconfiguration on my Registry.
(Push not authorized for this user)

Therefore the behaviour of the plugin is totally correct !

So sorry for the waste of time.
Thank you so much for the reply.

**Comment by tboerger** [comment]
Good to know. Just as a small sidenote, afaik you should just write the repo, without the registry for `repo:`

**Comment by athieriot** [comment]
Thanks. I'm going to do that.

I've seen a mention of a fix for that situation in the issues but wasn't sure what was the preferred way.

**Comment by yizhishang** [comment]
how dou you get the "auth" data

> Thanks. I'm going to do that.
> 
> I've seen a mention of a fix for that situation in the issues but wasn't sure what was the preferred way.

how dou you get the "auth" data?

**Comment by yizhishang** [comment]
> Thanks. I'm going to do that.
> 
> I've seen a mention of a fix for that situation in the issues but wasn't sure what was the preferred way.

how dou you get the "auth" data

**Comment by yizhishang** [comment]
> Thanks. I'm going to do that.
> 
> I've seen a mention of a fix for that situation in the issues but wasn't sure what was the preferred way.

how dou you get the auth data like "T0K3N=="

**Comment by tboerger** [comment]
This issue is more than 3 years old...
