### ISSUE TITLE
dry run fails when no repo is provided

### ISSUE THREAD

**Issue by Berjou** [drone-plugins/drone-docker#292]
Hi.

I was not able to make a successful dry run build without providing a dummy repo, which seems to be an odd behavior since the goal of the `dry_run` setting is to not push the builded image, so the `repo` argument should not be necessary.

Is this behavior intended, or is there some technical difficulty to provide a more logical behavior?

**Comment by ashwilliams1** [comment]
This is expected.  The repo field is used to tag the image and if the repo is not provided, it cannot be properly tagged. The intended purpose of dry_run is to perform every task _except_ pushing to the registry.
