### ISSUE TITLE
Where is `/go/bin/drone-docker`

### ISSUE THREAD

**Issue by letusfly85** [drone-plugins/drone-docker#3]
Did you commit & push a file `drone-docker` ? :worried:

**Comment by bradrydzewski** [comment]
yep!  all plugins are auto-published on every commit. https://hub.docker.com/r/plugins/drone-docker/tags/

**Comment by letusfly85** [comment]
I want to say that there is no `drone-docker` on this github repository.

So, `docker build` will fail below. :worried: 

https://github.com/drone-plugins/drone-docker/blob/master/Dockerfile#L17

**Comment by letusfly85** [comment]
Sorry, I'll try `go build` at first.
Thank you!
