### ISSUE TITLE
Enable auth against multiple registries

### ISSUE THREAD

**Issue by PhilipBehrenberg** [drone-plugins/drone-docker#324]
### Issue
If a user needs to push the resulting image to a private registry they have to give the private registry's credentials, via `username` and `password`. This means that every build image will be pulled from DockerHub anonymously. This causes problems on a larger team where you can hit DockerHub's pull rate limit (100pulls/6hours).

### Proposal
Allow the user to, alternatively to user/pass, supply a imagePullSecret (like you can with drone) to the `plugins/docker` container. This would allow a user to give credentials for any number of registries, public and private. Pulling from DockerHub with AccountA and pushing to PrivateReg with AccountB.

**Comment by bradrydzewski** [comment]
:wave: hey there, this is supported by using the `config` setting like this:

```
- name: build
  image: plugins/docker
  settings:
    repo: foo
    config: |
      {
          "auths": {
              "https://index.docker.io/v1/": {
                  "auth": "c3R...zE2"
              }
          }
      }
```

or with a secret like this:

```
- name: build
  image: plugins/docker
  settings:
    repo: foo
    config:
      from_secret: bar
```
