### ISSUE TITLE
Tagging docker images with commit

### ISSUE THREAD

**Issue by emilebosch** [drone-plugins/drone-docker#35]
Hi all!
I can't seem to tag my docker images with the SHA and commits.

I've tried both and `$$DRONE_COMMIT` and `$DRONE_COMMIT` but to no avail.

The error I get is:

```
$ /usr/bin/docker tag lab.54hrs.com/leaplines/apps:latest lab.54hrs.com/leaplines/apps:$$DRONE_COMMIT
Error response from daemon: Illegal tag name ($$DRONE_COMMIT): only [A-Za-z0-9_.-] are allowed ('.' and '-' are NOT allowed in the initial), minimum 1, maximum 128 in length
[info] build failed (exit code 1)
```

```
publish:
  docker:
    registry: lab.54hrs.com
    email: not@found.com
    username: registry
    password: $$REGISTRY_PASSWORD
    repo: XX
    tag:
      - latest
      - $$DRONE_COMMIT
```

It seems that the variables are not interpolated. Is this correct? I would love it if i can tag my images with the SHA and branch and optionally the latest.

**Comment by bradrydzewski** [comment]
please see the following section of the docs, need to use `$$COMMIT`
http://readme.drone.io/usage/variables/#string-interpolation:2b8b8ac4006be88c769f5e3fd99b009a

feel free to ask these sort of questions in either [gitter](https://gitter.com/drone/drone) or our [forum](https://discuss.drone.io) and reserve the issue tracker for confirmed bugs
