### ISSUE TITLE
Add ability to automatically add in proxy settings

### ISSUE THREAD

**Issue by donny-dont** [drone-plugins/drone-docker#37]
Drone 1.9 added the ability to specify arguments on the command line for stuff like proxy values when building behind a proxy.

Would be great to have something like

```
publish:
  docker:
    use_proxy: true
```

Which would check the plugin for the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY values. If any of those it and its lowercase equivalent would be added to the --build-arg in the docker build command generated by Drone.

**Comment by bradrydzewski** [comment]
makes sense to me

**Comment by bradrydzewski** [comment]
alternatively, we could add them automatically, and use an `ignore_proxy` flag

**Comment by jackspirou** [comment]
@bradrydzewski @donny-dont I would prefer them automatically added in with `disable_proxy` to disable.

**Comment by zbcjackson** [comment]
Any updates on this issue?

**Comment by bradrydzewski** [comment]
This issue can be closed. We merged a patch from @donny-dont a while back that's adds this capability.

https://github.com/drone-plugins/drone-docker/commit/68050024dbfa75753c2c3fe466a8ff245dea6886

**Comment by zbcjackson** [comment]
Oh I misunderstood this issue. What I want is to pull base images using proxy during building the image, not just build args. So the proxy values should be add to daemon
