### ISSUE TITLE
Use commit tag name for tagging an image

### ISSUE THREAD

**Issue by grahovam** [drone-plugins/drone-docker#43]
So far, an image can be variably tagged with $$BRANCH, $$COMMIT or $$BUILD_NUMBER. It is not possible to use a commit tag, right? So that if I push a tag on my git repo, a docker build is being triggered with an image tag of the same tag name?

**Comment by bradrydzewski** [comment]
yep, you can use $$TAG ... you can also do `$${TAG##v}` to remove the `v` prefix on your tag name. You need to enable builds for tags, which can be done in your drone repository setting screen.

feel free to ask these sort of questions in the gitter room at https://gitter.im/drone/drone
