### ISSUE TITLE
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### ISSUE THREAD

**Issue by blandes** [drone-plugins/drone-docker#49]
So, I know this might be a very generic error but I'm starting to believe it's because of an old Dockerfile that you use. Could we possibly bump drone-docker to the newest FROM rancher/docker:v10.13?

Anyways, basically, I run my generic .drone.yml but when I do, Drone tells me that it cannot connect to the Docker daemon. I'm running the generic Drone from the catalog but I also made my own version following the normal procedures and still receive the same errors. I'm running both Drone versions on /var/run/docker.sock. 

I thought it was because it was a permissions error because of how I had Drone setup, but then I made both versions privileged and still no dice. It will not connect to the Docker daemon. E-mails and other notifications still work though.

Now that leads me to believe that it's not on my end but the workers that are spawned in the process. When Drone pulls from this repo, this Dockerfile's FROM rancher/docker:1.9.1 is what is reported. It will say the title error then it will report the docker info as 1.9.1 and not 10.13 that my host is reporting.

Could this possibly be the reason for this error?

**Comment by bradrydzewski** [comment]
please see the known issues / troubleshooting section of the docker plugin documentation http://readme.drone.io/plugins/docker/

if you have any further questions please use the [gitter channel](https://gitter.im/drone/drone) and we'll be happy to help. thanks!
