### ISSUE TITLE
Ability to inject/mount self-signed certificates bundle into container.

### ISSUE THREAD

**Issue by steve-gray** [drone-plugins/drone-docker#51]
When using chained images from multiple repositories, the insecure_registry mode only allows the initial registry to work. Subsequent/chained images from other registries (i.e. one per department/team) will fail because of the X509 error.

**Comment by steve-gray** [comment]
The root issue that seems to be causing our problems is that the version of Linux this is based on, deep, deep in the layer chain, has an old set of CA certificates.

We ported the entire logic/behaviour over to a custom CentOS7 based container and it's all working fine now - so I suspect this issue is twofold:

- Image is using old baseline, missing many common CA's (a quick compare versus CentOS7/Ubuntu latest)
- No way to inject custom certs bundle. Would allow us to use internal registry / self-signed and also mitigate issue of missing root public CA.

**Comment by bradrydzewski** [comment]
I believe this needs to be resolved at the Drone level with the ability to read-only mount certificate volumes into plugin containers. We can then update plugins to load these certs from well-known directories using something like https://github.com/jackspirou/syscerts

**Comment by sstine** [comment]
This would be a great improvement. The current workaround of using the `insecure` flag isn't ideal.

**Comment by bchivari** [comment]
+1 for the ability to inject certificates, by some means, into /etc/docker/certs.d/ to allow for a self-signed secure registry. I'm at the point now where, in the absence of this feature, I'm forced to explore other options for the generation of Docker images as build artifacts.

**Comment by bradrydzewski** [comment]
@bchivari you can always fork the plugin and inject your certificate, or mount your certificate into the plugin as a volume (0.5 only)

```
pipeline:
  ...
  publish:
    image: plugins/docker
    ...
    volumes:
      - /etc/docker/certs.d:/etc/docker/certs.d
```

There are plans to expose a global certificate pool to all plugins (not just docker) but that isn't something that will be ready in the near term.  In the mean time, there should be sufficient workarounds available to proceed even if you require a custom certificate.

**Comment by bradrydzewski** [comment]
If anyone is interested in contributing an implementation of the global cert pool please contact us in our gitter channel to discuss further. https://gitter.im/drone/drone

If not, please note that it is not something I'm actively working on in the near term. If you have to wait for me to do it, it could take months.

**Comment by bradrydzewski** [comment]
drone now supports a global `DRONE_VOLUME` parameter. This is a global server setting that instructs drone to mount folders in all containers and can be used to mount custom certificate chains.

```
DRONE_VOLUME=/etc/ssl/certs:/etc/ssl/certs
```
