### ISSUE TITLE
Getting "unauthorized: authentication required" when pushing to public docker.io repo

### ISSUE THREAD

**Issue by schugh** [drone-plugins/drone-docker#52]
I even tried to insert the token after running docker login locally. i don't have any push restrictions on the provided account and was able to create the image just using the same commands that the plugin attempts:

$> docker build --pull=true --rm=true -f Dockerfile -t docker.io/stayfari/golang:latest .
$> docker tag docker.io/stayfari/golang:latest docker.io/stayfari/golang:1.6.2
$> docker push docker.io/stayfari/golang:latest

I do see that the login attempt succeeds and writes a config.json but it doesn't seem like its found when latter docker commands are run?

**My .drone.yml:**

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: 'docker.io'
    repo: 'stayfari/golang'
    email: 'email@email.com'
    username: 'username' 
    password: 'pa$$word' 
    auth: 'tokeN=='
    tag:
      - latest
      - '1.6.2'
    storage_driver: overlay
    file: Dockerfile
    insecure: false

**My output (starting at successful login):**
time="2016-04-28T17:37:10.805593708Z" level=info msg="POST /v1.21/auth" 
WARNING: login credentials saved in /.docker/config.json
Login Succeeded
$ /usr/bin/docker version
time="2016-04-28T17:37:11.945716342Z" level=info msg="GET /v1.21/version" 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
$ /usr/bin/docker info
time="2016-04-28T17:37:11.984750143Z" level=info msg="GET /v1.21/info" 
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.6-coreos
Operating System: <unknown> (containerized)
CPUs: 2
Total Memory: 3.855 GiB
Name: 3e5d9b5d14e9
ID: EDHP:3LXX:N73P:3FVU:VSME:2EGX:D56X:7BTL:3W36:BIWR:XAVI:777Y
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 19
 System Time: 2016-04-28T17:37:11.985961473Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
$ /usr/bin/docker build --pull=true --rm=true -f Dockerfile -t index.docker.io/v1/stayfari/golang:latest .
time="2016-04-28T17:37:12.028837166Z" level=info msg="POST /v1.21/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&pull=1&rm=1&t=index.docker.io%2Fv1%2Fstayfari%2Fgolang%3Alatest&ulimits=null" 
Sending build context to Docker daemon 100.9 kB
Sending build context to Docker daemon 100.9 kB

Step 1 : FROM golang:1.6.2
1.6.2: Pulling from library/golang
70e9a6907f10: Pulling fs layer
...
d4228319d724: Pull complete
Digest: sha256:4e3aca89aefc5b5b0722f31e1eeafc607937eb936717b2674a4088b55412d818
Status: Downloaded newer image for golang:1.6.2
 ---> d4228319d724
Step 2 : ENV GO15VENDOREXPERIMENT "1"
 ---> Running in 737306ce8a78
 ---> f24a652aa594
Removing intermediate container 737306ce8a78
Step 3 : RUN go get -u github.com/FiloSottile/gvt
 ---> Running in b32f97263cdc
 ---> cb63191207cd
Removing intermediate container b32f97263cdc
Successfully built cb63191207cd
$ /usr/bin/docker tag index.docker.io/v1/stayfari/golang:latest index.docker.io/v1/stayfari/golang:1.6.2
time="2016-04-28T17:38:01.845710555Z" level=info msg="POST /v1.21/images/index.docker.io/v1/stayfari/golang:latest/tag?repo=index.docker.io%2Fv1%2Fstayfari%2Fgolang&tag=1.6.2" 
$ /usr/bin/docker push index.docker.io/v1/stayfari/golang:latest
time="2016-04-28T17:38:01.883856311Z" level=info msg="POST /v1.21/images/index.docker.io/v1/stayfari/golang/push?tag=latest" 
The push refers to a repository [docker.io/v1/stayfari/golang] (len: 1)
cb63191207cd: Preparing
unauthorized: authentication required
[info] build failed (exit code 1)

**Comment by bradrydzewski** [comment]
I am [unable to reproduce](http://beta.drone.io/drone/drone/418) this error using the latest version of the plugin. There are also no reports of this issue from other users, and this is a heavily used plugin (50k+ downloads). 

This leads me to believe there may be configuration or environment issues. Also please note there have been known issues where Docker login is successful but pushing images failed. It is therefore entirely possible this is not a Drone issue (especially since I cannot repeat)
https://github.com/docker/distribution/issues/1165#issuecomment-155188266

The only thing I can think of is that you have misconfigured the registry value. It expects a fully qualified url and defaults to https://index.docker.io/v1/. Perhaps the login steps handles the misconfigured value but the publish step does not?

Since I cannot reproduce locally I'm not going to be able to resolve this issue for you. It is possible to execute plugins directly from the command line to test them in isolation. I recommend building and testing the plugin locally and reporting back the root cause if you are able to identify.

**Comment by schugh** [comment]
Hey Brad

Thanks for getting back to me so quickly.. I got it working by dropping the
'registry' config all together.

I'm running 0.4.2 (which i upgraded to after your email response) and no
change in the behavior.

For the sake of documenting, I tried for the value of 'registry':

docker.io   -- same failure
index.docker.io   --same failure
index.docker.io/v1  --same failure
https://index.docker.io/v1/   --hated the https://

guess the the 'registry' value is truly reserved for all registries other
than docker.io

Thanks again and love the project
-Samir

**Comment by bradrydzewski** [comment]
great, glad to hear removing the registry entry resolved this issue!
