### ISSUE TITLE
Use official docker in docker image

### ISSUE THREAD

**Issue by donny-dont** [drone-plugins/drone-docker#57]
Any reason we aren't using https://hub.docker.com/_/docker/ instead of the rancher base?

**Comment by gtaylor** [comment]
I haven't been following along. Does this get us anything new, or is this just a cleanliness thing?

**Comment by donny-dont** [comment]
@gtaylor I was having issues getting the docker plugin going in my 0.5 install. Switching to the official image ended up solving this. I'm not sure if it'll also help other users as well. It also had a later version of Docker 1.11. Also the image appeared to be a smaller size though imagelayers never wanted to find the rancher/docker container.
