### ISSUE TITLE
Push into custom Registry doesn't seem to work

### ISSUE THREAD

**Issue by cherry4477** [drone-plugins/drone-docker#59]
here is my configuration:
publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    Registry: registry.dataos.io
    Insecure: true
    Repo: datahubdevelop
    Username: dangsha
    Password: password
    Email: aaa
    file: Dockerfile
    Tag: $$COMMIT
    when:
      branch: develop
      event: push

the logs tells that login failed. 
could anyone tell me why,thank you for the help

**Comment by tboerger** [comment]
First of all you should use code tags to format this kind of information properly.

Than you should follow the docs correctly, the keys are case-sensitive.

Finally you should provide proper debug information like exact logging output

**Comment by cherry4477** [comment]
hi,thank u for your reply.

i'v changed my kernel to Linux ip-172-31-7-195 4.4.0-040400-generic

and here's the docker info:

Containers: 2
Images: 61
Storage Driver: devicemapper
 Pool Name: docker-202:1-678026-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.804 GB
 Data Space Total: 107.4 GB
 Data Space Available: 12.89 GB
 Metadata Space Used: 3.142 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Kernel Version: 4.4.0-040400-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 14.94 GiB
Name: ip-172-31-7-195
ID: XDKE:6OR4:Z6BX:42BJ:MJDW:XYXU:CH3W:C5SN:ER3J:2UQS:UWJG:SZZU
WARNING: No swap limit support


and the output:

Drone Docker Plugin built from 35c94a1
$ /usr/bin/docker -d -s devicemapper --insecure-registry registry.dataos.io
Warning: '-d' is deprecated, it will be removed soon. See usage.
time="2016-06-13T08:56:30Z" level=warning msg="please use 'docker daemon' instead." 
time="2016-06-13T08:56:30.285986159Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option" 
time="2016-06-13T08:56:30.287292067Z" level=info msg="API listen on /var/run/docker.sock" 
time="2016-06-13T08:56:30.307636178Z" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section." 
time="2016-06-13T08:56:30.336084039Z" level=warning msg="XFS is not supported in your system. Either the kernel doesnt support it or mkfs.xfs is not in your PATH. Defaulting to ext4 filesystem" 
time="2016-06-13T08:56:30.336173072Z" level=fatal msg="Error starting daemon: error initializing graphdriver: exec: \"mkfs.ext4\": executable file not found in $PATH" 
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Login failed.
[info] build failed (exit code 1)

**Comment by bradrydzewski** [comment]
please see the docker plugin documentation which describes this error ... devicemapper is not supported http://readme.drone.io/plugins/docker/

**Comment by cherry4477** [comment]
hi, thank u for your help~

It can be successfully when there's only the publish part as below:

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: registry.dataos.io
    #mirror: registry.dataos.io
    #image_name: registry.dataos.io/datahubdevelop/sub
    repo: datahubdevelop/sub
    username: admin
    password: 9999    
    email: mengjing@asiainfo.com
    #file: Dockerfile
    #Tag: $$COMMIT
    #when:
    #  branch: develop
    # event: push 

However, when merged into the build process, it failed

compose:
  database:
    image: registry.dataos.io/library/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=1234

build:
  image: golang
  branch: develop
  environment:
    - MYSQL_PORT_3306_TCP_ADDR=127.0.0.1
    - MYSQL_PORT_3306_TCP_PORT=3306
    - MYSQL_ENV_MYSQL_DATABASE=test
    - MYSQL_ENV_MYSQL_USER=root
    - MYSQL_ENV_MYSQL_PASSWORD=1234
    - MYSQL_CONFIG_DONT_UPGRADE_TABLES=yes
  commands:
    - mkdir -p /drone/src/github.com/asiainfoLDP
    - mv -f /drone/src/github.com/cherry4477/datahub_subscriptions /drone/src/github.com/asiainfoLDP/
    - export GOPATH=/drone
    - go get github.com/tools/godep
    - cd /drone/src/github.com/asiainfoLDP/datahub_subscriptions
    - $GOPATH/bin/godep restore
    - _db/initdb_v1.0.sh
    - go test -v -cover ./....
    - go build
    
publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: registry.dataos.io
    #mirror: registry.dataos.io
    #image_name: registry.dataos.io/datahubdevelop/sub
    repo: datahubdevelop/sub
    username: admin
    password: 9999    
    email: mengjing@asiainfo.com
    #file: Dockerfile
    #Tag: $$COMMIT
    #when:
    #  branch: develop
    # event: push

the logs are:

,\"job\":{\"id\":35,\"number\":1,\"status\":\"running\",\"exit_code\":0,\"enqueued_at\":1466044645,\"started_at\":1466044646,\"finished_at\":0,\"environment\":{}},\"vargs\":{\"email\":\"mengjing@asiainfo.com\",\"password\":\"9999\",\"registry\":\"registry.dataos.io\",\"repo\":\"datahubdevelop/sub\",\"storage_driver\":\"aufs\",\"username\":\"admin\"}}]" 
time="2016-06-16T02:39:35.037531629Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-06-16T02:39:35.038434618Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1" 
time="2016-06-16T02:39:35.039053862Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2016-06-16T02:39:35.062924673Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address" 
time="2016-06-16T02:39:35.118208687Z" level=warning msg="Your kernel does not support swap memory limit." 
time="2016-06-16T02:39:35.119322092Z" level=info msg="Daemon has completed initialization" 
time="2016-06-16T02:39:35.119346056Z" level=info msg="Docker daemon" commit=c3959b1 execdriver=native-0.2 graphdriver=aufs version=1.10.2 
time="2016-06-16T02:39:35.125025976Z" level=info msg="API listen on /var/run/docker.sock" 
Login failed.
[info] build failed (exit code 1)

could u help me?thank u (*^__^*)


孟静 （Meng Jing)    LDP云平台部

北京亚信智慧数据科技有限公司
地址：北京市海淀区中关村软件园二期亚信研发中心大厦
电话：010-8216 6212
手机：15010076116
邮件：mengjing@asiainfo.com
网站：www.asiainfodata.com
 
From: Brad Rydzewski
Date: 2016-06-14 00:53
To: drone-plugins/drone-docker
CC: cherry4477; Author
Subject: Re: [drone-plugins/drone-docker] Push into custom Registry doesn't seem to work (#59)
please see the docker plugin documentation which describes this error ... devicemapper is not supported http://readme.drone.io/plugins/docker/
―

**Comment by bradrydzewski** [comment]
See the common errors section that talks about swap limit http://readme.drone.io/plugins/docker/

**Comment by cherry4477** [comment]
hi, i'v added cgroup_enable=memory swapaccount=1 to my grub.cfg, but that does not work~   my os is ubuntu



孟静 （Meng Jing)    LDP云平台部

北京亚信智慧数据科技有限公司
地址：北京市海淀区中关村软件园二期亚信研发中心大厦
电话：010-8216 6212
手机：15010076116
邮件：mengjing@asiainfo.com
网站：www.asiainfodata.com
 
From: Brad Rydzewski
Date: 2016-06-16 11:22
To: drone-plugins/drone-docker
CC: cherry4477; Author
Subject: Re: [drone-plugins/drone-docker] Push into custom Registry doesn't seem to work (#59)
See the common errors section that talks about swap limit http://readme.drone.io/plugins/docker/
―

**Comment by cherry4477** [comment]
it is so strange:

compose:
  database:
    image: registry.dataos.io/library/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=1234

build:
  image: golang
  branch: develop
  environment:
    - MYSQL_PORT_3306_TCP_ADDR=127.0.0.1
    - MYSQL_PORT_3306_TCP_PORT=3306
    - MYSQL_ENV_MYSQL_DATABASE=test
    - MYSQL_ENV_MYSQL_USER=root
    - MYSQL_ENV_MYSQL_PASSWORD=1234
    - MYSQL_CONFIG_DONT_UPGRADE_TABLES=yes
  commands:
    - mkdir -p /drone/src/github.com/asiainfoLDP
    - mv -f /drone/src/github.com/cherry4477/datahub_subscriptions /drone/src/github.com/asiainfoLDP/
    - export GOPATH=/drone
    - go get github.com/tools/godep
    - cd /drone/src/github.com/asiainfoLDP/datahub_subscriptions
    - $GOPATH/bin/godep restore
    - _db/initdb_v1.0.sh
    - go test -v -cover ./....
    - go build
  notify:
    email:
      from: drone@github.com
      host: mail.asiainfo.com
      username: mengjing
      password: 12345
      recipients:
        - mengjing@asiainfo.com
publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: registry.dataos.io
    #image_name: registry.dataos.io/datahubdevelop/sub
    repo: datahubdevelop/sub
    username: admin
    password: 9999
    email: mengjing@asiainfo.com
    #file: Dockerfile
    #Tag: $$COMMIT
    #when:
    #  branch: develop
    # event: push

if i remove the section below in commands it can be successful
    - mv -f /drone/src/github.com/cherry4477/datahub_subscriptions /drone/src/github.com/asiainfoLDP/
    - export GOPATH=/drone
    - go get github.com/tools/godep
    - cd /drone/src/github.com/asiainfoLDP/datahub_subscriptions
    - $GOPATH/bin/godep restore
    - _db/initdb_v1.0.sh
    - go test -v -cover ./....
    - go build

why......



孟静 （Meng Jing)    LDP云平台部

北京亚信智慧数据科技有限公司
地址：北京市海淀区中关村软件园二期亚信研发中心大厦
电话：010-8216 6212
手机：15010076116
邮件：mengjing@asiainfo.com
网站：www.asiainfodata.com
 
From: Brad Rydzewski
Date: 2016-06-16 11:22
To: drone-plugins/drone-docker
CC: cherry4477; Author
Subject: Re: [drone-plugins/drone-docker] Push into custom Registry doesn't seem to work (#59)
See the common errors section that talks about swap limit http://readme.drone.io/plugins/docker/
―

**Comment by cherry4477** [comment]
it is solved. because mv -f  removes the dir /drone/src/github.com/cherry4477/datahub_subscriptions,which is needed in the docker container, i changed the mv to cp, it works
