### ISSUE TITLE
Private docker registry with letsencrypt

### ISSUE THREAD

**Issue by morero** [drone-plugins/drone-docker#60]
Hi,

Thanks for a great project.

Setting up a stack on rancheros/rancher, with a private docker registry, gogs and drone.
Can't seem to get the publish from drone-docker-plugin to my private registry working.

I am probably missing something.

I'm using letsencrypt for SSL in the registry, and can't get the dind-docker used by drone-docker-plugin to trust the certificate.

Is there a good way to do this? Can I inject an alternate image for dind with the root cert, or similar?

//Robin

**Comment by gintsgints** [comment]
Some additional information would be useful. Please give your job configuration details and any output logs you have with errors.
Also to have more debug you can use debug environment variable. (check README)

**Comment by tboerger** [comment]
Hi Robin,

generally it's difficult to inject something. We've got 2 options here.

1) https://github.com/docker-library/docker/blob/master/1.11/dind/Dockerfile gets an update to support Let's Encrypt
2) You build your own drone-docker image that includes root certificates that work for you.

As you can see we are just using the official image from Docker Inc. itself which seems to be not supporting Let's Encrypt.

@bradrydzewski or do you have any plans to extend the official images to accept Let's Encrypt?

**Comment by morero** [comment]
Hi,

Thanks for the help.

I've been using option 2 for a while now, and it's working fine, so I'll just stick with that for now.

As you say, it's probably better to include the  ISRG Root X1 somewhere down the chain, in docker, or alpine.

Was thinking that this might be a common scenario with a known workaround.

Ok with me to close.

Again, thanks!

//Robin

**Comment by bradrydzewski** [comment]
I am going to close this since it seems to be an upstream issue with the Alpine base images. I do not have any plans to manage custom certificate chains in the drone images at this time.
