### ISSUE TITLE
Unable to resolve rubygems.org on newest drone-docker image

### ISSUE THREAD

**Issue by sondinhinfectious** [drone-plugins/drone-docker#62]
I'm running Drone at commit `a9c84d26e11ffeb97311a1b549c48589dac95292` right now.

Before the latest drone-docker container push, our `bundle install` calls worked as expected.

Now, we get a bunch of `Gem::RemoteFetcher::UnknownHostError: timed out (...)` messages before our build fails.

Running `docker exec -it <container id> /bin/sh` onto the actual docker plugin container and then attempting to `curl rubygems.org` shows that the host can't be found. Calls to other sites such as https://google.com/ work. Is this anything to do with the new dind base image?

I've created a minimal repository showing this behaviour:
https://github.com/sondinhinfectious/drone-docker-gems

Here are the verbose logs:
https://gist.github.com/sondinhinfectious/f2d8ad289e320dc31a11be06b96d50bf

Docker info:
```
Containers: 110
Images: 212
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1014
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-61-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 2
Total Memory: 7.305 GiB
Name: drone-1
ID: SOXP:RKX2:MR5P:PDFH:QVJZ:4MKI:MGX2:LIYN:RGFP:GXOZ:3QJY:UVT5
WARNING: No swap limit support
```

```
$ uname --all
Linux drone-1 3.19.0-61-generic #69~14.04.1-Ubuntu SMP Thu Jun 9 09:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bradrydzewski** [comment]
I am unable to reproduce

```
Step 7 : RUN curl http://rubygems.org
 ---> Running in 74f93b22729d
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 ---> 7a09f4b36258
Removing intermediate container 74f93b22729d
Successfully built 7a09f4b36258
+ /usr/local/bin/docker tag c0ed34450e3fbdd5369c09ed5ffd02a9cff0ee75 foo:latest
```
