### ISSUE TITLE
Would like more complex, programmatic tags.

### ISSUE THREAD

**Issue by jgreat** [drone-plugins/drone-docker#65]
We would like to use a tagging scheme based on the version of our nodejs applications defined in in the project package.json file. There doesn't seem to be way to inject this into Drone at build time. 

See #64 for a possible implementation using a simple yaml file created as a build task.

**Comment by jmccann** [comment]
@bradrydzewski I think this can now be closed?

**Comment by andrewmclagan** [comment]
Yeah seems to work.
