### ISSUE TITLE
Private registry login failing

### ISSUE THREAD

**Issue by shaivyamahajan** [drone-plugins/drone-docker#66]
I'm having some issues with private registry pulls (using basic auth behind nginx).  The drone **build section** is able to authenticate and pull images from the private registry just fine, but the drone-docker plugin seems to fail to push the image

plugin failure log (from drone):
```
time="2016-07-22T06:36:15.872816337Z" level=error msg="Handler for POST /v1.22/auth returned error: Login: 404 page not found\n (Code: 404; Headers: map[Content-Length:[19] Docker-Distribution-Api-Version:[registry/2.0] X-Content-Type-Options:[nosniff] Server:[nginx/1.9.15] Date:[Fri, 22 Jul 2016 06:36:15 GMT] Content-Type:[text/plain; charset=utf-8]])" 
Error response from daemon: Login: 404 page not found
 (Code: 404; Headers: map[Content-Length:[19] Docker-Distribution-Api-Version:[registry/2.0] X-Content-Type-Options:[nosniff] Server:[nginx/1.9.15] Date:[Fri, 22 Jul 2016 06:36:15 GMT] Content-Type:[text/plain; charset=utf-8]])
Login failed.
[info] build failed (exit code 1)
```

Nginx log when **build section** pulls an image: 
```
[22/Jul/2016:06:36:07 +0000] "GET /v2/ HTTP/1.1" 401 195 "-" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
droneci [22/Jul/2016:06:36:07 +0000] "GET /v2/build/node6/manifests/latest HTTP/1.1" 200 1777 "-" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.16.0-4-amd64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
```

Nginx log when **drone-docker** tries to auth:
```
[22/Jul/2016:06:36:15 +0000] "GET /v2/ HTTP/1.1" 401 195 "-" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.16.0-4-amd64 os/linux arch/amd64"
[22/Jul/2016:06:36:15 +0000] "GET /v1/_ping HTTP/1.1" 401 195 "-" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.16.0-4-amd64 os/linux arch/amd64"
[22/Jul/2016:06:36:15 +0000] "POST /v1/users/ HTTP/1.1" 401 195 "-" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.16.0-4-amd64 os/linux arch/amd64"
droneci [22/Jul/2016:06:36:15 +0000] "GET /v1/users/ HTTP/1.1" 404 19 "-" "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.16.0-4-amd64 os/linux arch/amd64
```

Is this because the docker version is out of date ? (1.10.2 for publish vs 1.11.2 for build)  The actual authentication seems fine but it seems to hit the wrong URL for the next step?

**Comment by bradrydzewski** [comment]
> Is this because the docker version is out of date ? (1.10.2 for publish vs 1.11.2 for build) The actual authentication seems fine but it seems to hit the wrong URL for the next step?

the master branch uses Docker 1.11

here are instructions for running the plugin locally, without having to run a drone build:
https://github.com/drone-plugins/drone-docker#usage

I recommend trying to build / run the plugin locally and debugging. If you find an issue with the plugin feel free to send a pull request.

**Comment by arthurvi** [comment]
@shaivyamahajan I have the exact same issue and was thinking about version mismatch too. Did you find a solution for your problem?

**Comment by shaivyamahajan** [comment]
@arthurvi I tried to re-build the plugin image using docker 1.11.2 but it still could not connect to my private registry.  I gave up after that, have not been able to integrate drone into our build system because of it.

**Comment by donny-dont** [comment]
@shaivyamahajan @arthurvi can you please follow Brad's debugging instructions above? If there's something wrong with the plugin it would be great to get it fixed but that's not possible without help from users like you :smile: as we don't have every setup under the sun.

**Comment by arthurvi** [comment]
@shaivyamahajan I think I found the solution yesterday. There is a header problem when you use Nginx as proxy. The docker registry expects the header `Docker-Distribution-Api-Version registry/2.0` to be set. For some reason Nginx as proxy leads to an undefined header. You can solve it by adding this into the `location { }` block:
```
add_header 'Docker-Distribution-Api-Version' 'registry/2.0' always;
```
For more info check:
- [Other discussion about same issue](https://github.com/docker/distribution/issues/397)
- [Docker registry recipe for authenticating proxy with nginx](https://docs.docker.com/registry/recipes/nginx/)
