### ISSUE TITLE
Login failure with username with - in the name

### ISSUE THREAD

**Issue by irairdon** [drone-plugins/drone-docker#70]
I am trying to use the plugin to publish a docker image to an internal docker registry. The username has a "-" in the name (example: user-name). I looks like because of this we are facing this error.

$ /usr/bin/docker daemon -g /drone/docker
Error response from daemon: Registration: "Wrong username format (it has to match \"^[a-z0-9]{4,30}$\")"
Login failed.

**Comment by bradrydzewski** [comment]
this error message is either coming from your registry or from the docker daemon, not from this plugin. Therefore I recommend opening an issue with your registry or with docker / dockerhub
