### ISSUE TITLE
Authentication fails to private docker registry with empty email

### ISSUE THREAD

**Issue by meetmatt** [drone-plugins/drone-docker#86]
Drone 0.4 with plugins/drone-docker:latest (as of today).
I have a self-hosted private docker registry v2 set up with basic auth.
Authenticating to my registry doesn't require email, which conflicts with how `docker login` is implemented here: https://github.com/drone-plugins/drone-docker/blob/release/0.4/main.go#L147
However in master branch you have it fixed, so the email is optional.
I am in progress of implementing a fix for branch/0.4 (https://github.com/meetmatt/drone-docker).
Pull request to come.

**Comment by meetmatt** [comment]
#87

**Comment by meetmatt** [comment]
Still getting an error on my drone setup.
```
[info] Pulling image plugins/drone-docker:latest
Drone Docker Plugin built at 2016-07-29 06:41:09 UTC
$ /usr/bin/docker daemon -g /drone/docker -s overlay
Email: EOF
Login failed.
[info] build failed (exit code 1)
```
Have you updated the actual docker image?

**Comment by meetmatt** [comment]
@tboerger could you please update the actual docker image?

**Comment by tboerger** [comment]
It should be updated when @bradrydzewski updates the org secrets to match `plugins/docker` instead of `docker`.

**Comment by jalberto** [comment]
is the current image in dockerhub fixed with this?

I have same problem trying to login in an azure private registry

**Comment by jalberto** [comment]
![screenshot from 2017-02-19 16-41-04](https://cloud.githubusercontent.com/assets/99927/23104267/4f6518b4-f6c2-11e6-939f-07dd617b8e0f.png)

**Comment by donny-dont** [comment]
@jalberto that is the 0.4 plugin which is not seeing updates. The 0.5 version is [here](https://hub.docker.com/r/plugins/docker/)

**Comment by jalberto** [comment]
So I guess drone by default uses 0.5? Or must I set drone to use it?

I tried every combination I can think but every time get same error.
In local I can login with same credentials.

I also tried to run the container locally with same options, I don't get
any error but it seems like is not even trying to push the image

**Comment by donny-dont** [comment]
In 0.5 `image` is mandatory. In 0.4 the plugins would figure out the `image` automagically based on the name. I'm not sure what you are running but in 0.4 and 0.5 I've been able to push internal images with the docker plugin. You should try the discourse site or gitter if you need more immediate attention as that is a better way to get direct support and helps the Drone community provide better support.

**Comment by jalberto** [comment]
thanks @donny-dont
