### ISSUE TITLE
Docs at readme.drone.io/0.5/ are not in sync with DOCS.md

### ISSUE THREAD

**Issue by timoweiss** [drone-plugins/drone-docker#96]
Hey,

I just wanted to fix a property name (`file` to `dockerfile`) in the documentation. But I found that the https://github.com/drone-plugins/drone-docker/blob/master/DOCS.md are already correct.

Would you mind updating docs online? :)

Thank you!

**Comment by tboerger** [comment]
The documentation is in a flux and we know that. But thank you for the report.
