### ISSUE TITLE
Upgrade plugin to use Docker 1.12

### ISSUE THREAD

**Issue by mceyberg** [drone-plugins/drone-docker#97]
Docker 1.12 provides some new functionality such as the HEALTHCHECK directive.  It would be nice to update the plugin to incorporate Docker version 1.12 to take advantage of the newest updates and features of Docker.

**Comment by tuxity** [comment]
There is #88 and #98 waiting for approval, for 0.4 and 0.5

**Comment by tuxity** [comment]
@bradrydzewski

**Comment by bradrydzewski** [comment]
updated in c77a19918a14695bf34eb4e5112dda891a2ffaf2
