### ISSUE TITLE
Add support for the --squash flag

### ISSUE THREAD

**Issue by promag** [drone-plugins/drone-docker#99]
See docker/docker#22641.

**Comment by promag** [comment]
WDYT @bradrydzewski?

**Comment by tuxity** [comment]
The only thing with this feature, we have to enable the --experimental flag too
I'm gonna start something here https://github.com/tuxity/drone-docker/tree/docker-1.13 

The --cache-from flag is also pretty cool

**Comment by tuxity** [comment]
see #100

**Comment by bradrydzewski** [comment]
closing, added by #100
